export const Livros = [
  {
    id: 1,
    name: "Vidas secas",
    price: 19,
    image: "https://m.media-amazon.com/images/I/61kIG+4RESL._SY466_.jpg",
    author: "Graciliano Ramos",
    description:
      "Um dos maiores clássicos da literatura brasileira e retrato de uma época, Vidas secas traz a história de uma família que, procurando uma vida melhor, enfrenta a seca do sertão, a fome, o desamparo e a violência das instituições.",
    genre: "Romance Regionalista",
    publisher: "Record",
    publication_year: 1938,
    isbn: "9788501001115",
    rating: 4.7,
  },
  {
    id: 2,
    name: "Declínio de um Homem",
    price: 40,
    image: "https://m.media-amazon.com/images/I/81sblL-t2iL._SY466_.jpg",
    author: "Osamu Dazai",
    description:
      "A curta passagem pela vida do escritor japonês Osamu Dazai - suicidou-se aos 38 anos de idade - não o impediu de se transformar num autor bastante popular. Declínio de um homem, editado pela primeira vez no Brasil, vendeu mais de 10 milhões de exemplares desde sua publicação original, em 1948. A obra sintetiza em cenas e passagens notoriamente biográficas muitas das angústias que tanto alimentavam a personalidade autodestrutiva do autor, a saber: a dificuldade de entendimento com seus familiares, sua antissociabilidade niilista, seu patológico apego ao álcool - vício do qual nunca conseguiu se livrar -, sua autoestima inexistente, enfim, sua evidente sensação de deslocamento em relação ao mundo - como se tivesse sido enviado à existência por mero descuido.",
    genre: "Romance Autobiográfico",
    publisher: "Estação Liberdade",
    publication_year: 1948,
    isbn: "9788574482651",
    rating: 4.5,
  },
  {
    id: 3,
    name: "Memórias do subsolo",
    price: 43.37,
    image: "https://m.media-amazon.com/images/I/81b1DD3RZ-L._SY466_.jpg",
    author: "Fiódor Dostoiévski",
    description:
      "Obra-prima da literatura mundial, esta pequena novela traz, em embrião, vários temas da fase madura de Dostoiévski. Seu protagonista, um funcionário que vive no subsolo de um edifício em São Petersburgo, expõe a sua visão de mundo num discurso explosivo, labiríntico, vertido impecavelmente para o português por Boris Schnaiderman. Tradução primorosa. (Luciano Trigo, O Globo)",
    genre: "Romance Filosófico",
    publisher: "Editora 34",
    publication_year: 1864,
    isbn: "9788573261394",
    rating: 4.6,
  },
  {
    id: 4,
    name: "A metamorfose",
    price: 40.51,
    image: "https://m.media-amazon.com/images/I/71QLwli7GUL._SY466_.jpg",
    author: "Franz Kafka",
    description:
      "A metamorfose é a mais célebre novela de Franz Kafka e uma das mais importantes de toda a história da literatura. Sem a menor cerimônia, o texto coloca o leitor diante de um caixeiro-viajante - o famoso Gregor Samsa - transformado em inseto monstruoso. A partir daí, a história é narrada com um realismo inesperado que associa o inverossímil e o senso de humor ao que é trágico, grotesco e cruel na condição humana - tudo no estilo transparente e perfeito desse mestre inconfundível da ficção universal.",
    genre: "Novela Existencialista",
    publisher: "Companhia das Letras",
    publication_year: 1915,
    isbn: "9788535902778",
    rating: 4.8,
  },
  {
    id: 5,
    name: "Capitães da areia",
    price: 42.86,
    image: "https://m.media-amazon.com/images/I/81t7altQZxL._SY425_.jpg",
    author: "Jorge Amado",
    description:
      "Capitães da Areia, a história crua e comovente de meninos pobres que moram num trapiche abandonado em Salvador, é talvez o romance mais influente de Jorge Amado. Clássico absoluto dos livros sobre a infância abandonada, assombrou e encantou várias gerações de leitores e permanece hoje tão atual quanto na época em que foi escrito.",
    genre: "Romance Social",
    publisher: "Companhia das Letras",
    publication_year: 1937,
    isbn: "9788535908053",
    rating: 4.7,
  },
  {
    id: 6,
    name: "Casa velha",
    price: 15.67,
    image: "https://m.media-amazon.com/images/I/81TunxkWsSL._SY466_.jpg",
    author: "Machado de Assis",
    description:
      "Publicado em folhetim entre os anos de 1885 e 1886, Casa Velha é o sexto romance de Machado de Assis. Redescoberta pela pesquisadora Lúcia Miguel Pereira em 1944, a obra é a menos conhecida pelo grande público. O livro é narrado por um padre que decide escrever uma obra política sobre o Primeiro Reinado de D. Pedro I.",
    genre: "Romance Histórico",
    publisher: "Martin Claret",
    publication_year: 1885,
    isbn: "9788572324274",
    rating: 4.2,
  },
  {
    id: 7,
    name: "O mito de Sísifo",
    price: 42.28,
    image: "https://m.media-amazon.com/images/I/81ccIcOmAoL._SY466_.jpg",
    author: "Albert Camus",
    description:
      "De um dos mais importantes e representativos autores do século XX e Prêmio Nobel de Literatura, O mito de sísifo traz ensaios sobre o absurdo e o irracional, tornando-se uma importante contribuição filosófico-existencial que exerce influência profunda sobre toda uma geração.",
    genre: "Ensaio Filosófico",
    publisher: "Record",
    publication_year: 1942,
    isbn: "9788501083166",
    rating: 4.6,
  },
  {
    id: 8,
    name: "O idiota",
    price: 90.44,
    image: "https://m.media-amazon.com/images/I/81yztS6pgeL._SY425_.jpg",
    author: "Fiódor Dostoiévski",
    description:
      "Nova edição, revista pelo tradutor, de O idiota, um dos grandes romances de Dostoiévski, trazendo a série completa de ilustrações de Oswaldo Goeldi. Publicado originalmente em 1868, este é um desses livros em que o leitor reconhece de imediato a marca do gênio.",
    genre: "Romance Clássico",
    publisher: "Editora 34",
    publication_year: 1868,
    isbn: "9788573266146",
    rating: 4.8,
  },
  {
    id: 9,
    name: "A hora da estrela",
    price: 26.16,
    image: "https://m.media-amazon.com/images/I/61TaHURu27L._SY342_.jpg",
    author: "Clarice Lispector",
    description:
      "Pouco antes de morrer, em 1977, Clarice Lispector decide se afastar da inflexão intimista que caracteriza sua escrita para desafiar a realidade. O resultado desse salto na extroversão é A hora da estrela, o livro mais surpreendente que escreveu.",
    genre: "Romance Psicológico",
    publisher: "Rocco",
    publication_year: 1977,
    isbn: "9788532508416",
    rating: 4.5,
  },
  {
    id: 10,
    name: "Noites Brancas",
    price: 35.24,
    image: "https://m.media-amazon.com/images/I/7143D7foVmL._SY466_.jpg",
    author: "Fiódor Dostoiévski",
    description:
      "Durante uma das maravilhosas noites brancas do verão de São Petersburgo, em que o sol praticamente não se põe, dois jovens se encontram numa ponte sobre o rio Nievá, dando início a uma história carregada de fantasia, emoção e lirismo.",
    genre: "Novela Romântica",
    publisher: "L&PM",
    publication_year: 1848,
    isbn: "9788525423948",
    rating: 4.4,
  },
  {
    id: 11,
    name: "Livro do desassossego",
    price: 24.5,
    image: "https://m.media-amazon.com/images/I/51yAXUUteyL._SY466_.jpg",
    author: "Fernando Pessoa",
    description:
      "Os fragmentos que compõem esta complexa obra representam a inquietude, os sentimentos, as dúvidas e o amplo conhecimento de mundo daquele que segurava a caneta para escrever tão profundas palavras e ao fim assinar sob o semi-heterônimo de Bernardo Soares.",
    genre: "Prosa Poética",
    publisher: "Companhia das Letras",
    publication_year: 1982,
    isbn: "9788535928198",
    rating: 4.6,
  },
  {
    id: 12,
    name: "O velho e o mar",
    price: 41.27,
    image: "https://m.media-amazon.com/images/I/71wo6d7Ex3L._SY466_.jpg",
    author: "Ernest Hemingway",
    description:
      "Depois de anos na profissão, havia 84 dias que o velho pescador Santiago não apanhava um único peixe. Por isso já diziam se tratar de um salão, ou seja, um azarento da pior espécie. Mas ele possui coragem, acredita em si mesmo, e parte sozinho para alto-mar.",
    genre: "Novela",
    publisher: "Bertrand Brasil",
    publication_year: 1952,
    isbn: "9788528613056",
    rating: 4.7,
  },
  {
    id: 13,
    name: "Dom Quixote",
    price: 59.9,
    image: "https://m.media-amazon.com/images/I/51WRC2c-rNL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "Miguel de Cervantes",
    description:
      "A história do cavaleiro errante Dom Quixote e seu fiel escudeiro Sancho Pança é uma das obras-primas da literatura mundial. Publicada em duas partes (1605 e 1615), a novela satiriza os romances de cavalaria e explora temas como idealismo, realidade e a busca por justiça em um mundo imperfeito.",
    genre: "Romance de Cavalaria",
    publisher: "Companhia das Letras",
    publication_year: 1605,
    isbn: "9788535914849",
    rating: 4.9,
  },
  {
    id: 14,
    name: "Orgulho e Preconceito",
    price: 34.9,
    image: "https://m.media-amazon.com/images/I/41HF69KafUS._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "Jane Austen",
    description:
      "Um clássico da literatura inglesa, Orgulho e Preconceito acompanha Elizabeth Bennet, uma jovem inteligente e espirituosa, enquanto navega por questões de amor, casamento, classe social e expectativas culturais na Inglaterra do início do século XIX.",
    genre: "Romance",
    publisher: "Martin Claret",
    publication_year: 1813,
    isbn: "9788572329989",
    rating: 4.8,
  },
  {
    id: 15,
    name: "Cem Anos de Solidão",
    price: 49.9,
    image: "https://m.media-amazon.com/images/I/511NRhFHZbL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "Gabriel García Márquez",
    description:
      "Um marco do realismo mágico, Cem Anos de Solidão narra a saga da família Buendía ao longo de sete gerações na fictícia cidade de Macondo, explorando temas de solidão, destino e repetição histórica.",
    genre: "Realismo Mágico",
    publisher: "Record",
    publication_year: 1967,
    isbn: "9788501078087",
    rating: 4.9,
  },
  {
    id: 16,
    name: "Matar um Rouxinol",
    price: 39.9,
    image: "https://m.media-amazon.com/images/I/41BXQGdYmcL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "Harper Lee",
    description:
      "Um clássico da literatura americana, Matar um Rouxinol aborda racismo e injustiça no sul dos EUA através dos olhos de Scout Finch, uma jovem que observa seu pai, o advogado Atticus Finch, defender um homem negro acusado injustamente.",
    genre: "Romance Social",
    publisher: "José Olympio",
    publication_year: 1960,
    isbn: "9788503011273",
    rating: 4.8,
  },
  {
    id: 17,
    name: "1984",
    price: 29.9,
    image: "https://m.media-amazon.com/images/I/51VXYaKO-sL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "George Orwell",
    description:
      "Uma distopia clássica, 1984 apresenta um mundo totalitário onde o governo controla todos os aspectos da vida, vigiando os cidadãos através do Big Brother. Winston Smith tenta resistir à opressão, mas enfrenta as consequências de sua rebelião.",
    genre: "Distopia",
    publisher: "Companhia das Letras",
    publication_year: 1949,
    isbn: "9788535914849",
    rating: 4.9,
  },
  {
    id: 18,
    name: "O Grande Gatsby",
    price: 35.5,
    image: "https://m.media-amazon.com/images/I/41Pvw91bWZL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "F. Scott Fitzgerald",
    description:
      "Ambientado na era do jazz dos anos 1920, O Grande Gatsby explora o sonho americano através da vida de Jay Gatsby, um milionário misterioso obcecado por reconquistar seu amor perdido, Daisy Buchanan.",
    genre: "Romance",
    publisher: "Penguin Companhia",
    publication_year: 1925,
    isbn: "9788580860023",
    rating: 4.7,
  },
  {
    id: 19,
    name: "Madame Bovary",
    price: 42.0,
    image: "https://m.media-amazon.com/images/I/51befhIVaCL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "Gustave Flaubert",
    description:
      "Este romance realista acompanha Emma Bovary, uma mulher insatisfeita com sua vida provinciana que busca paixão e luxo através de casos extraconjugais, levando-a a uma tragédia de dívidas e desespero.",
    genre: "Romance Realista",
    publisher: "Zahar",
    publication_year: 1857,
    isbn: "9788537810125",
    rating: 4.6,
  },
  {
    id: 20,
    name: "A Odisséia",
    price: 45.0,
    image: "https://m.media-amazon.com/images/I/81pk1lQC0eL._SY342_.jpg",
    author: "Homero",
    description:
      "Um épico grego clássico, A Odisséia narra as aventuras de Odisseu em sua longa jornada de volta para casa após a Guerra de Troia, enfrentando criaturas míticas, deuses e desafios naturais.",
    genre: "Poesia Épica",
    publisher: "Martin Claret",
    publication_year: -800,
    isbn: "9788572329903",
    rating: 4.9,
  },
  {
    id: 21,
    name: "Mrs. Dalloway",
    price: 38.7,
    image: "https://m.media-amazon.com/images/I/51dHVm1a-4S._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "Virginia Woolf",
    description:
      "Este romance modernista acompanha um dia na vida de Clarissa Dalloway, uma socialite londrina, utilizando um estilo de fluxo de consciência para explorar temas de memória, trauma e pressões sociais.",
    genre: "Romance Modernista",
    publisher: "Autêntica",
    publication_year: 1925,
    isbn: "9788551306147",
    rating: 4.5,
  },
  {
    id: 22,
    name: "O Retrato de Dorian Gray",
    price: 31.9,
    image: "https://m.media-amazon.com/images/I/41Ou42L7UoL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "Oscar Wilde",
    description:
      "O único romance de Oscar Wilde explora a vaidade e a moralidade através de Dorian Gray, um jovem que troca sua alma por juventude eterna, enquanto seu retrato envelhece e reflete suas transgressões.",
    genre: "Romance Filosófico",
    publisher: "Penguin Companhia",
    publication_year: 1890,
    isbn: "9788580860030",
    rating: 4.7,
  },
  {
    id: 23,
    name: "O Senhor dos Anéis",
    price: 89.9,
    image: "https://m.media-amazon.com/images/I/41RBd2DvmgL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "J.R.R. Tolkien",
    description:
      "Uma trilogia épica de fantasia, O Senhor dos Anéis segue a jornada de Frodo Bolseiro para destruir um anel maligno que ameaça o mundo, acompanhado por uma irmandade de heróis.",
    genre: "Fantasia Épica",
    publisher: "HarperCollins Brasil",
    publication_year: 1954,
    isbn: "9788595086807",
    rating: 4.9,
  },
  {
    id: 24,
    name: "O Apanhador no Campo de Centeio",
    price: 37.8,
    image: "https://m.media-amazon.com/images/I/51Ooch+98bL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "J.D. Salinger",
    description:
      "Este romance de formação segue Holden Caulfield, um adolescente rebelde que, após ser expulso da escola, vagueia por Nova York, refletindo sobre alienação, autenticidade e a perda da inocência.",
    genre: "Romance de Formação",
    publisher: "Todavia",
    publication_year: 1951,
    isbn: "9788593828058",
    rating: 4.6,
  },
  {
    id: 25,
    name: "Vinte Mil Léguas Submarinas",
    price: 44.5,
    image: "https://m.media-amazon.com/images/I/61NXRmMz4eL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "Jules Verne",
    description:
      "Uma aventura de ficção científica, este romance segue o Professor Aronnax, seu servo Conseil e o arpoador Ned Land enquanto exploram o oceano a bordo do submarino Nautilus, comandado pelo enigmático Capitão Nemo.",
    genre: "Ficção Científica",
    publisher: "Zahar",
    publication_year: 1870,
    isbn: "9788537810132",
    rating: 4.5,
  },
  {
    id: 26,
    name: "Em Busca do Tempo Perdido",
    price: 79.9,
    image: "https://m.media-amazon.com/images/I/31kel96oE6L._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "Marcel Proust",
    description:
      "Uma obra monumental da literatura francesa, Em Busca do Tempo Perdido explora memória, amor e arte através das lembranças do narrador sobre sua vida na aristocracia francesa do final do século XIX.",
    genre: "Romance Modernista",
    publisher: "Globo Livros",
    publication_year: 1913,
    isbn: "9788525041593",
    rating: 4.8,
  },
  {
    id: 27,
    name: "A Revolução dos Bichos",
    price: 29.9,
    image: "https://m.media-amazon.com/images/I/61owA5ey3iL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "George Orwell",
    description:
      "Uma fábula satírica que critica o totalitarismo, A Revolução dos Bichos mostra animais de uma fazenda que se rebelam contra seus donos humanos, apenas para criar um regime igualmente opressivo.",
    genre: "Fábula Política",
    publisher: "Companhia das Letras",
    publication_year: 1945,
    isbn: "9788535910698",
    rating: 4.8,
  },
  {
    id: 28,
    name: "O Morro dos Ventos Uivantes",
    price: 36.9,
    image: "https://m.media-amazon.com/images/I/51sz0nn7u9L._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "Emily Brontë",
    description:
      "Um romance gótico intenso, O Morro dos Ventos Uivantes explora amor, vingança e obsessão através da trágica história de Heathcliff e Catherine Earnshaw nas charnecas inglesas.",
    genre: "Romance Gótico",
    publisher: "Martin Claret",
    publication_year: 1847,
    isbn: "9788572329910",
    rating: 4.7,
  },
  {
    id: 29,
    name: "Ulisses",
    price: 69.9,
    image: "https://m.media-amazon.com/images/I/51KMS5xWEWL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "James Joyce",
    description:
      "Um marco do modernismo, Ulisses narra um dia na vida de Leopold Bloom em Dublin, utilizando um estilo experimental e fluxo de consciência para explorar a condição humana.",
    genre: "Romance Modernista",
    publisher: "Companhia das Letras",
    publication_year: 1922,
    isbn: "9788535925142",
    rating: 4.6,
  },
  {
    id: 30,
    name: "As Vinhas da Ira",
    price: 47.5,
    image: "https://m.media-amazon.com/images/I/51cLAItFadL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "John Steinbeck",
    description:
      "Um retrato poderoso da Grande Depressão, As Vinhas da Ira segue a família Joad em sua migração da Oklahoma devastada pela seca para a Califórnia, enfrentando pobreza e injustiça.",
    genre: "Romance Social",
    publisher: "Record",
    publication_year: 1939,
    isbn: "9788501078094",
    rating: 4.8,
  },
  {
    id: 31,
    name: "O Estrangeiro",
    price: 33.9,
    image: "https://m.media-amazon.com/images/I/61cFRircgZL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "Albert Camus",
    description:
      "Um romance existencialista, O Estrangeiro acompanha Meursault, um homem indiferente à sociedade que se envolve em um crime e enfrenta as absurdidades da existência e da justiça humana.",
    genre: "Romance Existencialista",
    publisher: "Record",
    publication_year: 1942,
    isbn: "9788501083173",
    rating: 4.6,
  },
  {
    id: 32,
    name: "O Hobbit",
    price: 49.9,
    image: "https://m.media-amazon.com/images/I/511+-lOOtsL._SY445_SX342_ControlCacheEqualizer_.jpg",
    author: "J.R.R. Tolkien",
    description:
      "Uma aventura de fantasia, O Hobbit segue Bilbo Bolseiro, um hobbit relutante que se junta a um grupo de anões e ao mago Gandalf em uma missão para recuperar um tesouro guardado por um dragão.",
    genre: "Fantasia",
    publisher: "HarperCollins Brasil",
    publication_year: 1937,
    isbn: "9788595086791",
    rating: 4.8,
  },
];